# Ya que la línea 'version' es obsoleta, la he eliminado para no generar más warnings.

services:
  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mi_db
      - POSTGRES_USER=mi_usuario
      - POSTGRES_PASSWORD=mi_clave
    ports:
      - "5432:5432"

  # Servicio de la Aplicación Django
  web:
    build: .
    container_name: django_web
    command: >
      sh -c "chown -R root:root /app/media && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=mi_db
      - DB_USER=mi_usuario
      - DB_PASS=mi_clave
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: