version: '3.8'

services:
  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine  # Usar una imagen ligera de Postgres
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mi_db           # Nombre de tu base de datos
      - POSTGRES_USER=mi_usuario    # Usuario de la base de datos
      - POSTGRES_PASSWORD=mi_clave  # Contraseña súper secreta
    ports:
      - "5432:5432" # Opcional: para conectar desde tu PC si lo necesitas

  # Servicio de la Aplicación Django
  web:
    build: .  # Construye la imagen usando el Dockerfile en la carpeta actual
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app  # Mapea tu código local al contenedor para ver cambios en vivo
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=mi_db
      - DB_USER=mi_usuario
      - DB_PASS=mi_clave
      - DB_HOST=db       # ¡Importante! El host es el nombre del servicio de la BD
      - DB_PORT=5432
    depends_on:
      - db  # Le dice a Django que no inicie hasta que la BD esté lista

volumes:
  postgres_data: # Este volumen asegura que tus datos de la BD persistan