# Generated by Django 5.2.3 on 2025-06-24 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='boletines/portadas/', verbose_name='Portada')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_edit_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Edición')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='boletines/pdfs/', verbose_name='Archivo PDF')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletines_creados', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('last_edit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletines_editados', to=settings.AUTH_USER_MODEL, verbose_name='Autor de Última Edición')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boletines.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Boletín',
                'verbose_name_plural': 'Boletines',
                'ordering': ['-creation_date'],
            },
        ),
    ]
